### ISSUE TITLE
Anonymous replies reveals name during email notification

### ISSUE THREAD

**Issue by shawonibnkamal** [doclin-dev/doclin#132]
Doclin allows user to submit threads anonymously. 

<img width="439" alt="image" src="https://github.com/user-attachments/assets/7fbd0c23-fb51-45e6-b298-9b6c3a43215b">

When user tags someone's name in the thread, the tagged person receives an email notification. Currently, the email notification reveals the thread creators name which is a privacy breach.

Take a look at threadController.postThread. We need to pass in the anonymous check as an argument to sendMentionEmailNotification. Then use an condition to prevent senderName from revealing with the anonymous check is set to true.

**Comment by abhedanil** [comment]
Please assign it to me

**Comment by abhedanil** [comment]
Hi @shawonibnkamal , 
I've implemented the changes to ensure anonymous thread submissions do not reveal the sender's name in email notifications. I haven't been able to test this thoroughly due to some local setup issues. Could you please review the changes and suggest any necessary adjustments?

PR: https://github.com/doclin-dev/doclin/pull/140

Thank you!

**Comment by shawonibnkamal** [comment]
> Hi @shawonibnkamal , I've implemented the changes to ensure anonymous thread submissions do not reveal the sender's name in email notifications. I haven't been able to test this thoroughly due to some local setup issues. Could you please review the changes and suggest any necessary adjustments?
> 
> PR: #140
> 
> Thank you!

Thanks! Left some comments on your PR. Can you share what local setup issues you are facing? I can help fix those and improve the documentation as needed.

**Comment by abhedanil** [comment]
Update the PR (https://github.com/doclin-dev/doclin/pull/140) with suggested changes . I am not able the test the api endpoint to test the functionality in local
