### ISSUE TITLE
Replying to threads is not sending notification

### ISSUE THREAD

**Issue by shawonibnkamal** [doclin-dev/doclin#141]
In `replyController.ts`, sending notification is being handled under `sendEmailNotification` method.

```js
const allRelevantUserIds = [...new Set([...mentionedUserIds, ...relevantUserIds])];

if (mentionedUserIds.length > 0) {
  sendMentionEmailNotification(
    userId,
    allRelevantUserIds,
...
```
The if statement is using the wrong variable. It should check the length of `allRelevantUserIds` instead.

**Comment by temideewan** [comment]
@shawonibnkamal  I'd like to take this up

**Comment by shawonibnkamal** [comment]
Thank you @temideewan, I assigned you this issue.
