### ISSUE TITLE
Getting infinite loader when running the app locally. 

### ISSUE THREAD

**Issue by taprottoy** [doclin-dev/doclin#142]
During initial set up, when running the extension locally, clicking on `Run extension` /`Start debugging` open the app on debugger but the extension keeps loading. It fails to load the extension due to this error. 
```
notificationsAlerts.ts:40 Error: Cannot find module '/Users/././././doclin/extension/dist/extension.js'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
```

Probable Fix: 
Make sure to run `npm i` in the extension directory. After the `npm i` click on `Run extension`/`Start debuggin` to run the app. If it still throws error, navigate to the `doclin/extension/dist` folder. If the `extension.js` and `extesnion.map.js` exists then re-run the debugger. Rerunning the debugger should run load the extension properly.

**Comment by shawonibnkamal** [comment]
A missing step in README.md and CONTRIBUTING.md caused this issue. Under "Run the extension" we need to add these commands before running the debugger:

```
cd extension
npm install
```

Adding "good first issue" label to this.
