### ISSUE TITLE
Gracefully handle insufficient openai credit 

### ISSUE THREAD

**Issue by sameer-ahmd** [doclin-dev/doclin#146]
When running locally with an openai key with insufficient funds, the server crashes causing the extension to stop working.

```
Uncaught Exception: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by taprottoy** [comment]
Thank you @sameer-ahmd for creating the issue and bringing this to our attention. We have an open pull request on co-pilot so we will try to address this issue in that open PR or separately asap.
